config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'sessions#new'
  get '/auth/:provider/callback', to: 'sessions#omniauth'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create', as: 'login_post'
  get '/signup', to: 'users#new', as: 'new_user'
  get '/home', to: 'home#home'  
  post '/services/:id/copy', to: 'services#duplicate', as: 'duplicate_service'
  get  '/services/:service_id/work/:id', to: 'service_works#destroy', as: 'delete_service_work'
  delete '/logout', to: 'sessions#destroy', as: 'log_out'

  resources :services
  resources :works, only: :index
  resources :users, only: :create
  resources :composers, only: [:new, :create, :edit, :update]  do 
    resources :works
  end

end

app/models/service.rb
class Service < ApplicationRecord
    has_many :service_works
    has_many :user_services
    has_many :works, through: :service_works
    has_many :users, through: :user_services
    validates :start_time, presence: true
    validates :end_time, presence: true
    validate :start_time_is_before_end_time
    scope :rehearsals, -> {where(concert: false)}
    scope :all_chron, -> {order(:start_time)}
    scope :future, -> {where("start_time >= ?", DateTime.current-1)}


    
   
    def program
        self.works.order(:order)
    end

    def date
        self.start_time.strftime('%A, %B %d, %Y')
    end


    def start_time_is_before_end_time
        if start_time > end_time 
            errors.add(:start_date, "can't be in after the end time.")
        end
    end

   


end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
    before_action :set_service, only: [:show, :new, :edit, :update]
    before_action :set_service_works, only: [:create, :update]
    
    def index 
        @services = Service.all_chron.future
    end

    def show

    end
    
    def new

    end

    def create
        @service = Service.new(service_params)
        
        if @service.save
            create_or_update_service_works(@service_works)
            redirect_to service_path(@service)
        else
            render :new
        end
    end

    def edit 
           
    end

    def update
        if !@service.update(service_params) #if a service does not update render :edit form
            render :edit
        else
            create_or_update_service_works(@service_works)
            redirect_to service_path(@service)
        end
    end

    def destroy #try dependent destroy
        @service = Service.find(params[:id])
        @service.service_works.destroy_all
        @service.destroy
        redirect_to '/home'
    end

    def calendar

    end

    def duplicate
        @service = Service.find(params[:id])
        @dup_service = @service.dup
        
        if @dup_service.save 
            duplicate_service_works(@service, @dup_service.id)
            redirect_to edit_service_path(@dup_service)
        else 
            flash[:error] = "Service not copied! Please try again."
            redirect_to service_path(@service)
        end
    end

private 

    def service_params
        params.require(:service).permit(
            :date, 
            :start_time, 
            :end_time, 
            :concert
        )
    end

    def service_works_params
        params.require(:service).permit(
            service_works_attributes: [
                order: [],
                work_id: [],
                id: []
            ]
        )
    end

    def set_service
        if params[:id] && !Service.exists?(params[:id]) #find_by is an option
            redirect_to '/home'
        elsif params[:id]
            @service = Service.find(params[:id])
        else
            @service = Service.new 
        end
    end

    def set_service_works
        @service_works = service_works_params[:service_works_attributes]
    end

    def duplicate_service_works(service, dup_service_id)
        if service.service_works
            service.service_works.each do |service_work|
                dup_service_work = service_work.dup
                dup_service_work.service_id = dup_service_id
                dup_service_work.save
            end
        end
    end

    def create_or_update_service_works(service_works)
        service_works[:order].reject(&:empty?).each_with_index  do |order, i|
        
            if !service_works[:id][i].empty?
                work = ServiceWork.find(service_works[:id][i])
                work.order = order
                work.work_id = service_works[:work_id][i]
                work.save
            else 
                ServiceWork.create(work_id: service_works[:work_id][i], service_id: @service.id, order: order)
            end

        end
    end

end

app/helpers/services_helper.rb
module ServicesHelper

    def rehearsal_or_concert(service)
        if service.concert 
            "Concert"
        else
            "Rehearsal"
        end
    end

    def rehearsal_or_concert_abbreviated(service)
        if service.concert 
            "C:"
        else
            "R:"
        end
    end

    def service_duration_format(service)
        "#{service.start_time.strftime('%I:%M %P')} - #{service.end_time.strftime('%I:%M %P')}"
    end

    def service_date_format(service)
        "#{service.start_time.strftime('%A, %B %d, %Y')}"
    end

    def service_show_format(service)
        "#{service_date_format(service)} - #{service_duration_format(service)}"
    end

    def service_index_format(service)
        "#{service_show_format(service)} - #{rehearsal_or_concert(service)}"
    end

    
end

app/views/services/_form.html.erb
<%= render partial: 'errors/errors', locals: {object: service} %>
<hr>
    <%= form_for service do |f| %>
        <p><%= f.label :Start %>
        <%= f.datetime_select :start_time, :minute_step => 15 %></p>
        <p> <%= f.label :End %>
        <%= f.datetime_select :end_time, :minute_step => 15  %> </p>
        <p><%= f.label :Concert %>
        <%= f.check_box :concert %></p>
        <hr>
        <h3>Repertoire</h3> 
        <hr>
        
        <table>
            <tr>
                <th>Order</th>
                <th>Work</th>
            </tr>
            <%= f.fields_for :service_work, service.service_works.build do |w| %>
                <tr>
                    <td><%= w.number_field :order, {:name => 'service[service_works_attributes][order][]', :value => service.service_works[0].order}  %> </td>
                    <td><%= w.grouped_collection_select(:work_id, Composer.all, :works_in_alpha, :full_name, :id, :title, {:selected => service.service_works[0].work_id, :prompt => "Please Select a Work", :include_blank => false}, {:name => 'service[service_works_attributes][work_id][]' }) %></td>
                    <td><%= f.hidden_field :id, {:name => 'service[service_works_attributes][id][]', :value => service.service_works[0].id} %> </td>
                </tr>
            <%end%>

            <%= f.fields_for :service_work, service.service_works.build do |w| %>
                <tr>
                    <td><%= w.number_field :order, {:name => 'service[service_works_attributes][order][]', :value => service.service_works[1].order}  %> </td>
                    <td><%= w.grouped_collection_select(:work_id, Composer.all, :works_in_alpha, :full_name, :id, :title, {:selected => service.service_works[1].work_id, :prompt => "Please Select a Work", :include_blank => false}, {:name => 'service[service_works_attributes][work_id][]' }) %></td>
                    <td><%= f.hidden_field :id, {:name => 'service[service_works_attributes][id][]', :value => service.service_works[1].id} %> </td> 
                </tr>
            <%end%>

            <%= f.fields_for :service_work, service.service_works.build do |w| %>
                <tr>
                    <td><%= w.number_field :order, {:name => 'service[service_works_attributes][order][]', :value => service.service_works[2].order}  %> </td>
                    <td><%= w.grouped_collection_select(:work_id, Composer.all, :works_in_alpha, :full_name, :id, :title, {:selected => service.service_works[2].work_id, :prompt => "Please Select a Work", :include_blank => false}, {:name => 'service[service_works_attributes][work_id][]' }) %></td>
                    <td><%= f.hidden_field :id, {:name => 'service[service_works_attributes][id][]', :value => service.service_works[2].id} %> </td>
                </tr>
            <%end%>
        </table><br>
        <%= f.submit %>
    <% end %>

app/views/services/edit.html.erb
    <h2> Edit Service </h2>

<%= render partial: 'services/form', locals: {service: @service} %>

app/views/services/index.html.erb
<h2>Upcoming Services <%= link_to "Create New Service", new_service_path %></h2>

<hr>
<% @services.each do |service| %>
    <p class = "service"> <%=link_to service_index_format(service), service_path(service) %></p>
    <hr>
<% end %>

app/views/services/new.html.erb
    <h2> New Service </h2>

<%= render partial: 'services/form', locals: {service: @service} %>

app/views/services/show.html.erb
<b><i><%=flash[:error]%></i></b>
    <p><h2> <%=rehearsal_or_concert(@service)%> </h2> 
    <h3> <%=service_show_format(@service)%></h3>
    
    <hr>
    <h3> Repertoire </h3>
    
    <%@service.program.each do |work|%>
        <p><%= work.title%> - <%= work.composer.last_name %> <%=link_to "Remove", delete_service_work_path(@service.id, work.id), data: { confirm: "Are you sure you want to remove #{work.title}?" }, class: "service" %> </p>
    <% end %>
    <hr>
    <%=link_to "Edit", edit_service_path(@service)%> <%= link_to"New + Copy", duplicate_service_path(@service), method: :post,data: { confirm: "Are you sure you want to copy this service?" } %> <%= link_to "Delete", [@service], method: :delete, data: { confirm: "Are you sure you want to delete this service?" } %>