config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'sessions#new'
  get '/auth/:provider/callback', to: 'sessions#omniauth'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create', as: 'login_post'
  get '/signup', to: 'users#new', as: 'new_user'
  get '/home', to: 'home#home'  
  post '/services/:id/copy', to: 'services#duplicate', as: 'duplicate_service'
  get  '/services/:service_id/work/:id', to: 'service_works#destroy', as: 'delete_service_work'
  delete '/logout', to: 'sessions#destroy', as: 'log_out'

  resources :services
  resources :works, only: :index
  resources :users, only: :create
  resources :composers, only: [:new, :create, :edit, :update]  do 
    resources :works
  end

end

app/models/work.rb
class Work < ApplicationRecord
    belongs_to :composer
    has_many :service_works
    has_many :services, through: :service_works
    validates :title, presence: true
    scope :all_alpha, -> {order(:title)}
    
    
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
    before_action :set_composer, only: [:new, :edit, :create]
    before_action :set_work, only: [:show, :edit, :update, :destroy]
    
    def index
        if params[:search]
            @composers = Composer.search(params[:search]).by_last_name
        else
            @composers = Composer.all.by_last_name
        end
    end

    def show 
        
    end

    def new
        @work = @composer.works.build
    end

    def edit
        
    end

    def create 
        @work = Work.new(work_params)
        @work.composer_id = @composer.id

        if @work.save
            redirect_to composer_work_path(@composer, @work)
        else
            render :new
        end
    end

    def update
        if @work.update(work_params)
            redirect_to composer_work_path(@work)
        else
            render :edit
        end
    end

    def destroy
        @work.destroy
        redirect_to works_path
    end

    def service_works_new
        @works = Work.all
        @program = ServiceWork.new
    end

private 

    def work_params
        params.require(:work).permit(:title, :instrumentation)
    end

    def set_composer
        @composer = Composer.find(params[:composer_id])
    end

    def set_work 
        @work = Work.find(params[:id])
    end
end

app/helpers/works_helper.rb
module WorksHelper



    def composer_year_format(date)
        if date 
            date.strftime('%Y')
        end
    end

end

app/views/works/_composer_details.html.erb
<b>Birth:</b> <%=composer_year_format(composer.birth_year)%><br>
<b>Death:</b> <%=composer_year_format(composer.death_year)%><br>
<b>Epoch:</b> <%= composer.epoch %><br>

app/views/works/_form.html.erb
<%= render partial: 'errors/errors', locals: {object: work} %>

<%= form_for [composer, work] do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :instrumentation %>
    <%= f.text_field :instrumentation %>
    <%= f.submit %>
<% end %>

app/views/works/edit.html.erb
<h2>Create New Work</h2>
<hr>
Composer <b><%=@composer.full_name%></b>
<%= render partial: 'works/form', locals: {composer: @composer, work: @work} %>

app/views/works/index.html.erb
<h2> Works Library <%= link_to "Add Composer", new_composer_path %>  </h2> 

<%= form_tag(works_path, method: :get) do %>
    <%= text_field_tag 'search' %>
    <%= submit_tag 'Search'  %>
<% end %>



<hr>
<% @composers.each do |composer|%>
    <button type="button" class="collapsible"><%= composer.full_name %></button>
    <div class="content">
        <br>
        <b>Composer:</b> <%= composer.full_name %>  <%=link_to "Edit", edit_composer_path(composer)%><hr>

        <%= render partial: 'works/composer_details', locals: {composer: composer} %>
       
        <hr>
        <h3> Repertoire <%= link_to "Add New Work", new_composer_work_path(composer) %></h3>
        <hr>
      
            <% composer.works.each do |work| %>
                <%=link_to work.title, composer_work_path(composer, work)%> <%= link_to "Delete", [composer, work], method: :delete, data: { confirm: "Are you sure you want to delete this Work?" } %> <%=link_to "Edit", edit_composer_work_path(composer, work)%> <br>
            <% end %>
     
    </div>
<% end %>

<%= javascript_pack_tag 'index' %>

app/views/works/new.html.erb
<h2>Create New Work</h2>
<hr>
Composer <b><%=@composer.full_name%></b>

<%= render partial: 'works/form', locals: {composer: @composer, work: @work} %>

app/views/works/show.html.erb
<h2> <%= @work.title %> <%=link_to "Edit", edit_composer_work_path(@work.composer, @work)%></h2>

<b>Composer:</b> <%= @work.composer.full_name %><br>
<%= render partial: 'works/composer_details', locals: {composer: @work.composer} %>
<hr>
<h3>Instrumentation</h3>
<%= @work.instrumentation %>
<hr>
<%= link_to "Back", works_path %>