config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'sessions#new'
  get '/auth/:provider/callback', to: 'sessions#omniauth'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create', as: 'login_post'
  get '/signup', to: 'users#new', as: 'new_user'
  get '/home', to: 'home#home'  
  post '/services/:id/copy', to: 'services#duplicate', as: 'duplicate_service'
  get  '/services/:service_id/work/:id', to: 'service_works#destroy', as: 'delete_service_work'
  delete '/logout', to: 'sessions#destroy', as: 'log_out'

  resources :services
  resources :works, only: :index
  resources :users, only: :create
  resources :composers, only: [:new, :create, :edit, :update]  do 
    resources :works
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,600;0,700;0,800;1,300;1,400;1,600;1,700;1,800&display=swap" rel="stylesheet">
    <title>OrchestraNow</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if !current_user %>
    <div class="wrapper-login">
    <h1>orchestra<i><b>NOW</b></i></h1>
    <hr>
        <%= yield %>
    </div>
  <% else %>
      <header>
        <nav>
          <h1>orchestra<i><b>NOW</b></i></h1> 
          <ul>
            <li><%= link_to "Home", '/home' %></li>
            <li><%= link_to "Works", works_path %></li>
            <li><%= link_to "Upcoming Services", services_path %></li>
            <li><%= link_to "Log out", log_out_path, method: :delete, data: { confirm: "Are you sure you want to log out?" } %></li>
          </ul>
        </nav>
      </header>
        <div class= 'wrapper'>
          <%= yield %>
        </div>
  <% end %>
  </body>
</html>